theme: jekyll-theme-minimal
title: Personal Projects
author: Thalia Juarez
logo: /assets/img/logo.png
description: > # this means to ignore newlines until "baseurl:"
  Hello, Iâ€™m Thalia! I recently graduated from The University of Texas at Rio Grande 
  Valley as a computer science student. Here are a few projects I have worked on:

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  thaliajuarez # DO NOT include the @ character, or else the build will fail!
linkedin: thalia-juarez
show_excerpts: true # set to false to remove excerpts on the homepage
google_analytics:
